# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

annualized_return <- function(returns, period_per_year) {
    .Call('_RcppPerfCalc_annualized_return', PACKAGE = 'RcppPerfCalc', returns, period_per_year)
}

annualized_sd <- function(x, scale) {
    .Call('_RcppPerfCalc_annualized_sd', PACKAGE = 'RcppPerfCalc', x, scale)
}

annualized_dd <- function(returns, period_per_year) {
    .Call('_RcppPerfCalc_annualized_dd', PACKAGE = 'RcppPerfCalc', returns, period_per_year)
}

mdd <- function(returns) {
    .Call('_RcppPerfCalc_mdd', PACKAGE = 'RcppPerfCalc', returns)
}

